### PR TITLE
modifications after username change

### PR DESCRIPTION
**Pull request by rednepal**

### CODE REVIEW

**Comment by tvaspar** [comment]
Not quite there.

**Comment by rednepal** [comment]
What should be done?

**Comment by rednepal** [comment]
Trying now

**Comment by tvaspar** [comment]
Hmm, let me close it

**Comment by rednepal** [comment]
Hello

**Comment by rednepal** [comment]
Can we try now

**Comment by tvaspar** [comment]
Make a few more changes

**Pull request merged**
